#!/usr/bin/env bash
set -euo pipefail

TARGET_CONF="/etc/nginx/conf.d/cloudflare.conf"
TMP_CONF="${TARGET_CONF}.tmp"

CF_V4_URL="https://www.cloudflare.com/ips-v4"
CF_V6_URL="https://www.cloudflare.com/ips-v6"

mkdir -p "$(dirname "${TARGET_CONF}")"

{
  echo "# Auto-generated by update-cloudflare-real-ip.sh"
  echo "# Source: ${CF_V4_URL} and ${CF_V6_URL}"
  echo "# Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo ""
  echo "# Trust Cloudflare proxies for the real client IP"
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  echo ""
  echo "# Cloudflare IPv4 ranges"
  if curl -fsSL "${CF_V4_URL}" >/dev/null 2>&1; then
    curl -fsSL "${CF_V4_URL}" | sed 's/^/set_real_ip_from /; s/$/;/'
  else
    echo "# Warning: failed to fetch ${CF_V4_URL}" >&2
  fi
  echo ""
  echo "# Cloudflare IPv6 ranges"
  if curl -fsSL "${CF_V6_URL}" >/dev/null 2>&1; then
    curl -fsSL "${CF_V6_URL}" | sed 's/^/set_real_ip_from /; s/$/;/'
  else
    echo "# Warning: failed to fetch ${CF_V6_URL}" >&2
  fi
} > "${TMP_CONF}"

# Only replace if changed
if [ ! -f "${TARGET_CONF}" ] || ! cmp -s "${TMP_CONF}" "${TARGET_CONF}"; then
  mv "${TMP_CONF}" "${TARGET_CONF}"
else
  rm -f "${TMP_CONF}"
fi

exit 0


